services:
  - type: web
    name: saheli-backend
    runtime: python
    # This command tells Render to install all packages from your requirements.txt file
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: GROQ_API_KEY
        value: ""
        generateValue: true
